INSERT INTO "Localization" (resource, message, language, created_at, updated_at, deleted_at) VALUES ('UserNotFound-Err', 'Kullanıcı bulunamadı.', 'TR', CURRENT_DATE, null, null) ON CONFLICT DO NOTHING
INSERT INTO "Localization" (resource, message, language, created_at, updated_at, deleted_at) VALUES ('UserNotFound-Err', 'User not found.', 'EN', CURRENT_DATE, null, null) ON CONFLICT DO NOTHING
INSERT INTO "Localization" (resource, message, language, created_at, updated_at, deleted_at) VALUES ('UserAlreadyExists-Err', 'Kayıtlı kullanıcı.', 'TR', CURRENT_DATE, null, null) ON CONFLICT DO NOTHING
INSERT INTO "Localization" (resource, message, language, created_at, updated_at, deleted_at) VALUES ('UserAlreadyExists-Err', 'User already exists.', 'EN', CURRENT_DATE, null, null) ON CONFLICT DO NOTHING
INSERT INTO "Localization" (resource, message, language, created_at, updated_at, deleted_at) VALUES ('WrongCredentials-Err', 'Giriş bilgilerinizi kontrol ediniz.', 'TR', CURRENT_DATE, null, null) ON CONFLICT DO NOTHING
INSERT INTO "Localization" (resource, message, language, created_at, updated_at, deleted_at) VALUES ('WrongCredentials-Err', 'Check your credentials.', 'EN', CURRENT_DATE, null, null) ON CONFLICT DO NOTHING
INSERT INTO "Localization" (resource, message, language, created_at, updated_at, deleted_at) VALUES ('SomethingWentWrong-Err', 'Geçici süre işleminizi gerçekleştiremiyoruz.', 'TR', CURRENT_DATE, null, null) ON CONFLICT DO NOTHING
INSERT INTO "Localization" (resource, message, language, created_at, updated_at, deleted_at) VALUES ('SomethingWentWrong-Err', 'We are temporarily unable to process your transaction.', 'EN', CURRENT_DATE, null, null) ON CONFLICT DO NOTHING
INSERT INTO "Localization" (resource, message, language, created_at, updated_at, deleted_at) VALUES ('TodoNotFound-Err', 'Todo itemi bulunamadı.', 'TR', CURRENT_DATE, null, null) ON CONFLICT DO NOTHING
INSERT INTO "Localization" (resource, message, language, created_at, updated_at, deleted_at) VALUES ('TodoNotFound-Err', 'Todo item not found.', 'EN', CURRENT_DATE, null, null) ON CONFLICT DO NOTHING
INSERT INTO "Localization" (resource, message, language, created_at, updated_at, deleted_at) VALUES ('TodoCouldntCreate-Err', 'Todo itemi oluşturulamadı.', 'TR', CURRENT_DATE, null, null) ON CONFLICT DO NOTHING
INSERT INTO "Localization" (resource, message, language, created_at, updated_at, deleted_at) VALUES ('TodoCouldntCreate-Err', 'Todo item could not create.', 'EN', CURRENT_DATE, null, null) ON CONFLICT DO NOTHING
INSERT INTO "Localization" (resource, message, language, created_at, updated_at, deleted_at) VALUES ('TodoCouldntDelete-Err', 'Todo itemi silinemedi.', 'TR', CURRENT_DATE, null, null) ON CONFLICT DO NOTHING
INSERT INTO "Localization" (resource, message, language, created_at, updated_at, deleted_at) VALUES ('TodoCouldntDelete-Err', 'Todo item could not delete.', 'EN', CURRENT_DATE, null, null) ON CONFLICT DO NOTHING
INSERT INTO "Localization" (resource, message, language, created_at, updated_at, deleted_at) VALUES ('TodoCouldntUpdate-Err', 'Todo itemi güncellenemedi.', 'TR', CURRENT_DATE, null, null) ON CONFLICT DO NOTHING
INSERT INTO "Localization" (resource, message, language, created_at, updated_at, deleted_at) VALUES ('TodoCouldntUpdate-Err', 'Todo item could not update.', 'EN', CURRENT_DATE, null, null) ON CONFLICT DO NOTHING

INSERT IGNORE INTO Localization(resource, message, language, created_at, updated_at) VALUES('GlobalErrorMessage', 'Geçici süre işleminizi gerçekleştiremiyoruz.', 'TR', CURDATE(), CURDATE()) ON DUPLICATE KEY UPDATE resource = VALUES(resource), message = VALUES(message), language = VALUES(language);
INSERT IGNORE INTO Localization(resource, message, language, created_at, updated_at) VALUES('GlobalErrorMessage', 'We are temporarily unable to process your transaction.', 'EN', CURDATE(), CURDATE()) ON DUPLICATE KEY UPDATE resource = VALUES(resource), message = VALUES(message), language = VALUES(language);
INSERT IGNORE INTO Localization(resource, message, language, created_at, updated_at) VALUES('Err-1', 'Kullanıcı bulunamadı.', 'TR', CURDATE(), CURDATE()) ON DUPLICATE KEY UPDATE resource = VALUES(resource), message = VALUES(message), language = VALUES(language);
INSERT IGNORE INTO Localization(resource, message, language, created_at, updated_at) VALUES('Err-1', 'User not found.', 'EN', CURDATE(), CURDATE()) ON DUPLICATE KEY UPDATE resource = VALUES(resource), message = VALUES(message), language = VALUES(language);
INSERT IGNORE INTO Localization(resource, message, language, created_at, updated_at) VALUES('Err-2', 'Kayıtlı kullanıcı.', 'TR', CURDATE(), CURDATE()) ON DUPLICATE KEY UPDATE resource = VALUES(resource), message = VALUES(message), language = VALUES(language);
INSERT IGNORE INTO Localization(resource, message, language, created_at, updated_at) VALUES('Err-2', 'User already exists.', 'EN', CURDATE(), CURDATE()) ON DUPLICATE KEY UPDATE resource = VALUES(resource), message = VALUES(message), language = VALUES(language);
INSERT IGNORE INTO Localization(resource, message, language, created_at, updated_at) VALUES('Err-3', 'Lütfen geçerli bir e-mail adresi giriniz.', 'TR', CURDATE(), CURDATE()) ON DUPLICATE KEY UPDATE resource = VALUES(resource), message = VALUES(message), language = VALUES(language);
INSERT IGNORE INTO Localization(resource, message, language, created_at, updated_at) VALUES('Err-3', 'Please enter a valid e-mail.', 'EN', CURDATE(), CURDATE()) ON DUPLICATE KEY UPDATE resource = VALUES(resource), message = VALUES(message), language = VALUES(language);
INSERT IGNORE INTO Localization(resource, message, language, created_at, updated_at) VALUES('Err-4', 'Yanlış şifre girdiniz.', 'TR', CURDATE(), CURDATE()) ON DUPLICATE KEY UPDATE resource = VALUES(resource), message = VALUES(message), language = VALUES(language);
INSERT IGNORE INTO Localization(resource, message, language, created_at, updated_at) VALUES('Err-4', 'You entered the wrong password.', 'EN', CURDATE(), CURDATE()) ON DUPLICATE KEY UPDATE resource = VALUES(resource), message = VALUES(message), language = VALUES(language);
INSERT IGNORE INTO Localization(resource, message, language, created_at, updated_at) VALUES('Err-5', 'Şifrenizin uzunluğu minimum 6 karakter olmalı.', 'TR', CURDATE(), CURDATE()) ON DUPLICATE KEY UPDATE resource = VALUES(resource), message = VALUES(message), language = VALUES(language);
INSERT IGNORE INTO Localization(resource, message, language, created_at, updated_at) VALUES('Err-5', 'Your password length must be at least 6 characters.', 'EN', CURDATE(), CURDATE()) ON DUPLICATE KEY UPDATE resource = VALUES(resource), message = VALUES(message), language = VALUES(language);
INSERT IGNORE INTO Localization(resource, message, language, created_at, updated_at) VALUES('MAILHEADER', 'Merhaba,', 'TR', CURDATE(), CURDATE()) ON DUPLICATE KEY UPDATE resource = VALUES(resource), message = VALUES(message), language = VALUES(language);
INSERT IGNORE INTO Localization(resource, message, language, created_at, updated_at) VALUES('MAILHEADER', 'Hello,', 'EN', CURDATE(), CURDATE()) ON DUPLICATE KEY UPDATE resource = VALUES(resource), message = VALUES(message), language = VALUES(language);
INSERT IGNORE INTO Localization(resource, message, language, created_at, updated_at) VALUES('MAILTEXT', 'Türkçe Mail İçeriği', 'TR', CURDATE(), CURDATE()) ON DUPLICATE KEY UPDATE resource = VALUES(resource), message = VALUES(message), language = VALUES(language);
INSERT IGNORE INTO Localization(resource, message, language, created_at, updated_at) VALUES('MAILTEXT', 'İngilizce Mail İçeriği', 'EN', CURDATE(), CURDATE()) ON DUPLICATE KEY UPDATE resource = VALUES(resource), message = VALUES(message), language = VALUES(language);
INSERT IGNORE INTO Localization(resource, message, language, created_at, updated_at) VALUES('MAILSUBJECT', 'Anahtarınız', 'TR', CURDATE(), CURDATE()) ON DUPLICATE KEY UPDATE resource = VALUES(resource), message = VALUES(message), language = VALUES(language);
INSERT IGNORE INTO Localization(resource, message, language, created_at, updated_at) VALUES('MAILSUBJECT', 'Your Key', 'EN', CURDATE(), CURDATE()) ON DUPLICATE KEY UPDATE resource = VALUES(resource), message = VALUES(message), language = VALUES(language);